### PR TITLE
Adds farm-11 and farm-15 icons

### PR DESCRIPTION
**Pull request by emilymdubois**
sling your thoughts my way @natslaughter @samanpwbb

### CODE REVIEW

**Comment by natslaughter** [comment]
Hello @emilymdubois 
I think the farm icon is off to a great start. I was a little concerned that it looked too much like a generic building, but I think it will work seeing that there aren't many icons it will be competing with in rural / agricultural areas. 
I would merge it, however, Saman and I changed the filing structure of the icons folder. Not sure what will happen if I merge ... @samanpwbb or @emilymdubois can you provide some Git knowledge?

**Comment by natslaughter** [comment]
@emilymdubois,
Saman just told me you need to rebase against master, and move your icons out of the 'general' folder.

**Comment by emilymdubois** [comment]
Sounds great @natslaughter. Rebased and moved the `farm-1*.svg` files into the general `icons/` directory :ok_hand: Let me know if we find that these icons need tweaking to distinguish them from other structures!

cc @samanpwbb

**Comment by samanpwbb** [comment]
Hey @emilymdubois I think this a great start, definitely like the basic shape. 

It needs to be more pixel aligned. Right now at actual size it looks a bit blurry (especially on a non-retina screen). Here are a 
screen shot 2016-03-16 at 10 34 50 am

**Comment by emilymdubois** [comment]
@natslaughter @samanpwbb I attempted refining the pixel alignment for the two sizes. Hopefully it looks a little clearer now -- the only piece I couldn't get totally onto the grid without looking kind of weird was the barn window for the farm-11 icon. Let me know your thoughts!

**Comment by natslaughter** [comment]
Hello @emilymdubois!

The pixel alignment is good. I noticed a few other minor things. Once we address them, I think this icon will be ready.

1: I think the space between the barn and the silo needs to be a little bit greater, maybe .5 pixels more. For the 15 pixel icon, I find the barn to bee too wide, so that would help with that too. For the 15 pixel icon, you might want to even see what it looks like adding 1 pixel of additional space, but that might be too much ... not sure. 

screen shot 2016-03-22 at 9 18 01 am

screen shot 2016-03-22 at 9 23 31 am


2: I noticed on the silo geometry that the top isn't a circle. I would make it one, but that's just me

screen shot 2016-03-22 at 9 18 25 am



3: In the 11 pixel icon, there is a straggling line inside it.

screen shot 2016-03-22 at 9 20 04 am


That's it! Thanks again for the help. After the farm icon has been completed, do you want to select another one to draw?

**Comment by emilymdubois** [comment]
@natslaughter @samanpwbb is there a good way to increase the space between the barn and the silo while also staying pixel-aligned? 2 pixels between the farm and barn seem over-the-top, but 1.5 causes someone to fall out of alignment. Thoughts?

**Comment by natslaughter** [comment]
Hi @emilymdubois,
I think the icons are good to go.
It looks like there are some conflicts with the farm branch, to do with editing the source .ai files? Is it possible to resubmit just the svgs? 
Thanks!

**Comment by emilymdubois** [comment]
@natslaughter, removed my local edits to the `export` AI files, and added my :ear_of_rice: :cow2: layers to the `icons_design` AI files. Looks like we're in the green!

**Pull request merged**
